-- AlterTable
ALTER TABLE "Annotation" ADD COLUMN     "aiAnnotations" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "aiHoverCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "clickDelays" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "hoverDurations" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "interfaceVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "intervalAccuracy" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "intervalAgreement" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "labelAccuracy" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "labelAgreement" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "labelingTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mousePath" JSONB NOT NULL DEFAULT '[]';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "accuracy" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "agreement" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "engagementScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "interfaceSuggestion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "labelTimeAvg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "overreliance" DOUBLE PRECISION NOT NULL DEFAULT 0;
